services:
  queriocity:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file: env.local
    ports:
      - "8012:3000"
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
