/** Disclosure that the user is interacting with an AI system — EU AI Act Art 50(1).
 *
 *  Art 50(1) exempts cases where AI involvement is "obvious to a reasonably well-informed"
 *  person, which this arguably is. The exemption is not relied on: the Commission's guidelines
 *  discourage it, and Art 50(5) wants the notice at the first interaction anyway. */
export const AI_SYSTEM_NOTICE =
  'Queriocity is an AI system. Answers are generated by a language model and can be wrong — verify anything that matters.'

/** For the chat view, where the full notice would compete with the input on a phone. */
export const AI_SYSTEM_NOTICE_SHORT = 'AI-generated — verify anything that matters.'
