import { mkdir, unlink, writeFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import pkg from '../../../package.json' with { type: 'json' }
import { markPng } from '../../shared/ai-provenance.ts'

/** Provenance recorded in every generated image's metadata — EU AI Act Art 50(2). */
export const IMAGE_CREATOR_TOOL = `Queriocity ${pkg.version}`

// Diffusion runs are slow by nature (high step counts, large sizes, a shared GPU), so this
// only catches a genuinely stuck server rather than bounding normal work.
export const IMAGE_TIMEOUT_MS = parseInt(process.env.IMAGE_TIMEOUT_MS ?? '300000', 10)

export const IMAGE_STORAGE_DIR = process.env.IMAGE_STORAGE_DIR ?? '/tmp/queriocity/images'

/** Validated here rather than with a bare parseInt: these reach the diffusion server, and a NaN
 *  or zero produces a confusing remote error rather than an obvious local one. */
export function stepCount(raw: string | undefined, fallback: number): number {
  const n = parseInt(raw ?? '', 10)
  return Number.isFinite(n) && n > 0 ? n : fallback
}

/** Inference steps per quality tier. Configurable because the right values are a property of the
 *  model, not of this app: a timestep-distilled model (schnell, turbo, LCM) wants a handful, an
 *  SD1.5-era one wants 25+. Defaults suit a guidance-distilled FLUX-class model.
 *
 *  The server owns these — the quality wording in the prompt template deliberately names no
 *  numbers, so changing the env cannot leave a stale figure in the UI. */
export const IMAGE_STEPS = {
  draft: stepCount(process.env.IMAGE_STEPS_DRAFT, 8),
  balanced: stepCount(process.env.IMAGE_STEPS_BALANCED, 16),
  high: stepCount(process.env.IMAGE_STEPS_HIGH, 24),
}

export type ImageQuality = keyof typeof IMAGE_STEPS

/** Steps for a render, from the quality tier the model picked or an explicit count the user named.
 *
 *  Always resolves to a number, never to "unset": leaving the field out means the diffusion server
 *  applies its own default (20 for stable-diffusion.cpp), which silently ignores the configured
 *  tiers. The model is asked for the quality *word* rather than a count so the numbers stay here,
 *  where they are configurable, instead of depending on the model doing the lookup. */
export function resolveSteps(quality: ImageQuality | undefined, steps: number | undefined): number {
  if (steps !== undefined && steps > 0) return steps
  return IMAGE_STEPS[quality ?? 'balanced']
}

/** Seeds are a *signed* 32-bit int in practice, so this stops at 2^31-1 rather than 2^32-1.
 *
 *  Measured: stable-diffusion.cpp honours 2147483647 and silently randomises 2147483648, because a
 *  larger value parses as negative and negative conventionally means "pick one for me". With the
 *  unsigned bound, half of all generated seeds were quietly discarded and the render could not be
 *  reproduced from the seed we had logged. */
const SEED_MAX = 0x7fffffff

/** A seed for renders where the user did not pin one.
 *
 *  Sent explicitly rather than left unset, because servers disagree on what unset means:
 *  stable-diffusion.cpp substitutes a constant 42, so the same prompt returned the same image
 *  every time. Generating one here makes repeat renders vary on any backend. */
export const randomSeed = (): number => Math.floor(Math.random() * (SEED_MAX + 1))

/** Which request dialect the diffusion server speaks.
 *
 *  `openai` is the portable one, but its image schema has no room for a step count or a seed, so
 *  servers drop both — measured, not assumed. `sdapi` is the A1111 shape (`/sdapi/v1/txt2img`),
 *  where they are first-class fields, and is what stable-diffusion.cpp and A1111 both expose. */
export type ImageApi = 'openai' | 'sdapi'

export const IMAGE_API: ImageApi =
  process.env.IMAGE_API?.trim().toLowerCase() === 'sdapi' ? 'sdapi' : 'openai'

/** Only meaningful under `sdapi`; the OpenAI schema has nowhere to put it. Unset leaves the
 *  server's own default alone rather than guessing a value that suits one model family. */
export const IMAGE_CFG_SCALE = process.env.IMAGE_CFG_SCALE
  ? parseFloat(process.env.IMAGE_CFG_SCALE)
  : undefined

// Memo of image directories already mkdir'd, to skip the syscall. One entry per user, so it
// only needs a sanity bound rather than real eviction.
const createdImageDirs = new Set<string>()
const MAX_MEMOIZED_IMAGE_DIRS = 1000

/** Write generated bytes to the user's image directory, returning the URL to serve them from.
 *
 *  Provenance marking happens here so that no caller can add a route that stores an unmarked
 *  image — EU AI Act Art 50(2). */
export async function saveGeneratedImage(userId: string, bytes: Uint8Array): Promise<string> {
  const dir = `${IMAGE_STORAGE_DIR}/${userId}`
  if (!createdImageDirs.has(dir)) {
    await mkdir(dir, { recursive: true })
    if (createdImageDirs.size >= MAX_MEMOIZED_IMAGE_DIRS) createdImageDirs.clear()
    createdImageDirs.add(dir)
  }
  const filename = `${randomUUID()}.png`
  await writeFile(`${dir}/${filename}`, markPng(bytes, IMAGE_CREATOR_TOOL, process.env.IMAGE_MODEL))
  console.log(`  [image] saved ${userId}/${filename}`)
  return `/images/${userId}/${filename}`
}

const IMAGE_URL_RE = /!\[.*?\]\((\/images\/[\w-]+\/[\w-]+\.png)\)/g

/** Delete any generated image files referenced in the given message contents. */
export async function deleteSessionImages(contents: string[]): Promise<void> {
  const paths = new Set<string>()
  for (const content of contents) {
    for (const [, url] of content.matchAll(IMAGE_URL_RE)) {
      paths.add(`${IMAGE_STORAGE_DIR}/${url.slice('/images/'.length)}`)
    }
  }
  if (paths.size === 0) return
  await Promise.all([...paths].map(p =>
    unlink(p).catch(() => {}) // ignore missing files
  ))
  console.log(`  [image] deleted ${paths.size} file(s) for session`)
}
